require "date"
d = Date.today
Random.rand(0..35)

#質問のジャンルを登録
Qgenre.create!(id:1,genre:"飲み会")
Qgenre.create!(id:2,genre:"お金")
Qgenre.create!(id:3,genre:"雰囲気")
Qgenre.create!(id:4,genre:"恋愛")
Qgenre.create!(id:5,genre:"就活")
Qgenre.create!(id:6,genre:"勉強")
Qgenre.create!(id:7,genre:"その他")

#質問を登録
Question.create!(circle_id:1 ,
question_text:"飲み会はどんな感じですか？激しい？",
answer_text:"そこまで激しくないですよ！任意参加です！",qgenre_id:1)
Question.create!(circle_id:1 ,
question_text:"月にいくらくらいお金がかかりますか？",
answer_text:"イベント代,飲食代込で15000円位ですかね？",qgenre_id:2)
Question.create!(circle_id:1 ,
question_text:"先輩の雰囲気はどの感じですか？",
answer_text:"ノリの良い優しい人が多いです！",qgenre_id:3)
Question.create!(circle_id:1 ,
question_text:"飲み会はどんな感じですか？激しい？",
answer_text:"そこまで激しくないですよ！任意参加です！",qgenre_id:4)
Question.create!(circle_id:1 ,
question_text:"ぶっちゃけカップル多いですか？",
answer_text:"どうでしょう..?♡",qgenre_id:5)
Question.create!(circle_id:1 ,
question_text:"大学の勉強と両立可能ですか？",
answer_text:"全然可能です！過去問あげます！",qgenre_id:6)
Question.create!(circle_id:1 ,
question_text:"テニス未経験なんですけど,ついていけますかね？",
answer_text:"大丈夫！テニス未経験可です！",qgenre_id:7)

#サークルのジャンルは全てで36種類
Genre.create!(id:0,name:"テニス")
Genre.create!(name:"ダンス")
Genre.create!(name:"イベント系")
Genre.create!(name:"軽音")
Genre.create!(name:"ボランティア")
Genre.create!(name:"サッカー")
Genre.create!(name:"フットサル")
Genre.create!(name:"野球")
Genre.create!(name:"バスケ")
Genre.create!(name:"バレーボール")

Genre.create!(name:"チア")
Genre.create!(name:"スキー")
Genre.create!(name:"バドミントン")
Genre.create!(name:"スキューバ")
Genre.create!(name:"ハンドボール")
Genre.create!(name:"バレエ")
Genre.create!(name:"合気道")
Genre.create!(name:"スノボ")
Genre.create!(name:"クリケット")
Genre.create!(name:"陸上")

Genre.create!(name:"ラケットボール")
Genre.create!(name:"総合格闘技")
Genre.create!(name:"合唱")
Genre.create!(name:"器楽")
Genre.create!(name:"伝統芸能")
Genre.create!(name:"芸能文化")
Genre.create!(name:"メディア")
Genre.create!(name:"写真")
Genre.create!(name:"映像")
Genre.create!(name:"社会科学研究")

Genre.create!(name:"応援団")
Genre.create!(name:"文化系その他")
Genre.create!(name:"芸術")
Genre.create!(name:"自然科学研究")
Genre.create!(name:"人文科学研究")
Genre.create!(name:"表現")
Genre.create!(name:"DJ")

#同志社大学のサークルのデータ
#テニスサークル genre:0
Circle.create!(name: "LemonSquash",
               email: "example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "IMPERIAL",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動しています！",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス強い人多いよ！ガチ勢ウェルカム！",
               event: "月イチで飲み会開催！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "NOVICE",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "REGINA",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
               
Circle.create!(name: "同大硬式",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "テニス部",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")  

Circle.create!(name: "シルクロードTC",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "同志社硬式テニスサークルD.U.C.K",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
               
Circle.create!(name: "岡崎ソフトテニス同好会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "Revolutions",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")  

Circle.create!(name: "ALBATROSS",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "FLY_SPECK",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
               
Circle.create!(name: "PEANUTS",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "CREAM",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")  
          
Circle.create!(name: "COSMOS",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "白樺バニーズ",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
               
Circle.create!(name: "Check_mate",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "Green",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")  

Circle.create!(name: "WITTY",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "DOUBLE_FAULT",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
               
Circle.create!(name: "SMASH",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
        
Circle.create!(name: "e'tranger",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 0,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}回活動",
               sex: "#{Random.rand(0..10)}",
               introduction: "テニス大好き！な人募集中！",
               event: "土曜日に京都御所でテニスしてるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")  

#ダンス genre:1
Circle.create!(name: "Mimi_allure",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 1,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "踊りまくりたい人募集中！",
               event: "飲み会は全くありません！ストイックです！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
            
Circle.create!(name: "Ash",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 1,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "踊りまくりたい人募集中！",
               event: "飲み会は全くありません！ストイックです！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "同志社モダンジャズバレエサークル",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 1,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "踊りまくりたい人募集中！",
               event: "飲み会は全くありません！ストイックです！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Enchainement",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 1,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "踊りまくりたい人募集中！",
               event: "飲み会は全くありません！ストイックです！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Pichicart",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 1,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "踊りまくりたい人募集中！",
               event: "飲み会は全くありません！ストイックです！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Mayl_Mans",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 1,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "踊りまくりたい人募集中！",
               event: "飲み会は全くありません！ストイックです！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#イベント系 genre:2
Circle.create!(name: "Knit!",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 2,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "いろんなイベントがあります！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#軽音 genre:3
Circle.create!(name: "cock10",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 3,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バンドしたい人どうぞ！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "PENTA",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 3,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バンドしたい人どうぞ！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "P.S.",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 3,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バンドしたい人どうぞ！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#ボランティア genre:4
Circle.create!(name: "Shinmachi_Activate_Project",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "ASUVID今出川",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "ASUVID京田辺",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "Global_Baton_for_Ishinomaki",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "学生団体CHAD",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "スポーツボランティア団体Egg",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "PAZ_MUSICA",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社生涯スポーツ研究会~DUAL_Sport~",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "そら",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "STUDY FOR TWO",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 4,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "奉仕精神のある人がむいてるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#サッカー 5
Circle.create!(name: "LiBeRtA",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 5,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "サッカーやろうぜ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "JUEGO.FC",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 5,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "サッカーやろうぜ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Genius.F.C",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 5,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "サッカーやろうぜ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "ジーニアス",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 5,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "サッカーやろうぜ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "FC_PARTIRE",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 5,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "サッカーやろうぜ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Orange_Pigmon_FC",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 5,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "サッカーやろうぜ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#フットサル 6
Circle.create!(name: "FC無問題",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Galaxy",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "同志社フットサルクラブ女子",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "MAZEU",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "illusion ski club",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "FC_Dandy",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "FC.Eiffel",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "FC_VAMOS",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Ferret",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "GOLAZO",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "CASCAMOST",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "NOAH",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "RAFFICA",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 6,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "フットサルしまくろう！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#野球 7
Circle.create!(name: "MALTS",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "うるまライオンズ",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Oceans",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Cutters",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "I.W.HARPER",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "同志社大学新町野球サークルYandees",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "NigtBats",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Buffalo",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 7,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "元野球部求む！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#バスケ 8
Circle.create!(name: "LEOPARD",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 8,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "諦めたらそこで試合終了ですよ",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "DUNKO",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 8,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "諦めたらそこで試合終了ですよ",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#バレーボール 9
Circle.create!(name: "Hands-Up!",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 9,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バレーボール大会を目指して頑張ってます！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "SANDLOT",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 9,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バレーボール大会を目指して頑張ってます！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "DreamShake",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 9,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バレーボール大会を目指して頑張ってます！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
#チア 10
Circle.create!(name: "SWEETiEZ",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 10,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "チアガールになりたい人おいで！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "Jewels",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 10,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "チアガールになりたい人おいで！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")
#スキー 11


#バドミントン 12
Circle.create!(name: "BACCANO",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 11,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バド初心者でもwelcome！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "同志社バドミントン同好会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 11,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バド初心者でもwelcome！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#スキューバ 13
Circle.create!(name: "Drive In Blue",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 12,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "潜りたい人！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "同志社ダイビングポイント",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 12,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "潜りたい人！！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#ハンドボール 14
Circle.create!(name: "FUSIRAD",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 13,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ハンドボールいっぱいできるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#バレエ 15
Circle.create!(name: "PRITTS",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 15,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バレエをやりたい人大歓迎！",
               event: "体験会実施中！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "C.A.V",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 15,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バレエをやりたい人大歓迎！",
               event: "体験会実施中！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#合気道 16
Circle.create!(name: "同志社大学合気道同好会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 16,
               place: "学生会館#{Random.rand(1..5)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "護身術を学びたい女子もどうぞ！",
               event: "イベント盛り沢山だよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#スノボ 17
Circle.create!(name: "ハビッツ",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 17,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "雪好きあつまれええ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#クリケット 18
Circle.create!(name: "同志社クリケットサークル",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 18,
               place: "学生会館#{Random.rand(1..5)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "クリケットって何？って人は連絡ください！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#陸上 19
Circle.create!(name: "同志社陸上競技同好会クローバー会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 19,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "陸上好きあつまれ",
               event: "毎日走ってます",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#ラケットボール 20
Circle.create!(name: "Little-Goose",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 20,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ラケットボールになります",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")


#総合格闘技 21
Circle.create!(name: "Giorno",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 21,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "Rizin好きwelcome！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

#合唱 22
Circle.create!(name: "コールメイプル",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 22,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "合唱を本気でやりたい人おいで！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "NewSongs",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 22,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "合唱を本気でやりたい人おいで！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#器楽 23
Circle.create!(name: "radio_Naut",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 23,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "音楽好きおいでぇ〜",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#伝統芸能 24
Circle.create!(name: "小笠原流煎茶道道風会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 24,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "茶道好きは集まれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "小原流華道サークルいろどり",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 24,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "茶道好きは集まれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#芸能文化 25
Circle.create!(name: "同志社大学短歌会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 25,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "伝統的な短歌の世界に触れませんか",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "いみじ",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 25,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "伝統的な短歌の世界に触れませんか",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "古都研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 25,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "伝統的な短歌の世界に触れませんか",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")


#メディア 26
Circle.create!(name: "人権問題研究団体Pecorino",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 26,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "人権について考えませんか",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社大学PRESS",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 26,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "人権について考えませんか",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#写真 27

#映像 28
Circle.create!(name: "同志社ラブライブ部",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 28,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ラブライブ好き集まって！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#社会科学研究 29
Circle.create!(name: "Meilka同志社",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 29,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "社会科学を考えませんか？",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#応援団 30

#文化系その他 31
Circle.create!(name: "同志社バイクサークルAir",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"スポーツ系")

Circle.create!(name: "韓国料理研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "WoW2",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "決闘部",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "CATS&CAFE",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "教職研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社任天堂同好会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "たなっぷす",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "TED×Doshisha U",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "株式投資クラブwill",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "紅茶サークルSTAGE",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "下宿生支援サークルhomey",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社ポケモン同好会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "Fountain Commons",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "VOCALOID研究会_Arpeggio",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "英字新聞部",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "茶cha",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社NASA",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "中国人留学生学友会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "文華社",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社珈琲同好会彩月",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "ROJE(日本教育最高連盟)",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "S'il_vous_plait",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社音ゲーシンコウシンコウ会Do_it!",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社大学クイズ研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社アイマス研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "ゲームゲーム同志社ゲーム",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "BLC",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "韓国人留学生会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社大学TRENDサークルJAM",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社拉麺研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社大学ハロプロ研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社MONACA同好会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社ボードゲーム研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "同志社大学手芸サークル「もみの木」",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 31,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "バイク好きあつまれ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

#芸術 32 



#自然科学研究 33


#人文科学研究 34
Circle.create!(name: "同志社大学KGKイエス会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 34,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ハンドボールいっぱいできるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")
#表現 35
Circle.create!(name: "同志社大学落語研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 35,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ハンドボールいっぱいできるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "Doshisha_Shakespeare_Company",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 35,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ハンドボールいっぱいできるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "京田辺、演劇ないん会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 35,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ハンドボールいっぱいできるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")

Circle.create!(name: "京炎そでふれ！志舞踊",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 35,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "ハンドボールいっぱいできるよ！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")
#DJ 36
Circle.create!(name: "同志社大学音楽研究会",
               email: "#{Random.rand(0..10000000000)}example@railstutorial.org",
               password: "foobar",
               password_confirmation: "foobar",
               genre_id: 36,
               place: "学生会館#{Random.rand(1..9)}#{Random.rand(1..9)}#{Random.rand(1..9)}",
               frequency: "週#{Random.rand(1..8)}",
               sex: "#{Random.rand(0..10)}",
               introduction: "DJしたいひとあつまれい！",
               event: "飲み会もいっぱいあるよ！",
               sns: 'https://www.inazuma.jp/',
               admin: true,
               activated: true,
               activated_at: Time.zone.now,
               category:"文化系")